// <auto-generated />
using System;
using EverydayGirlsCompanionCollector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EverydayGirlsCompanionCollector.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126181941_V02_DataFoundations")]
    partial class V02_DataFoundations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Townie");

                    b.Property<string>("DisplayNameNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("TOWNIE");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDisplayNameChangeUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PartnerGirlId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayNameNormalized")
                        .HasDatabaseName("IX_AspNetUsers_DisplayNameNormalized");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PartnerGirlId");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_DisplayName_Valid", "LEN([DisplayName]) >= 4 AND LEN([DisplayName]) <= 16 AND [DisplayName] NOT LIKE '%[^a-zA-Z0-9]%'");
                        });
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.CompanionAssignment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GirlId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TownLocationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GirlId");

                    b.HasIndex("TownLocationId")
                        .HasDatabaseName("IX_CompanionAssignments_TownLocationId");

                    b.ToTable("CompanionAssignments");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.FriendRelationship", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FriendUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAddedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "FriendUserId");

                    b.HasIndex("FriendUserId")
                        .HasDatabaseName("IX_FriendRelationships_FriendUserId");

                    b.ToTable("FriendRelationships");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.Girl", b =>
                {
                    b.Property<int>("GirlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GirlId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GirlId");

                    b.ToTable("Girls");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.TownLocation", b =>
                {
                    b.Property<int>("TownLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownLocationId"));

                    b.Property<int>("BaseDailyBondGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("BaseDailyCurrencyGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("BaseDailySkillGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<bool>("IsLockedByDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("PrimarySkill")
                        .HasColumnType("tinyint");

                    b.Property<int>("UnlockCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.HasKey("TownLocationId");

                    b.ToTable("TownLocations");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.UserDailyState", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Candidate1GirlId")
                        .HasColumnType("int");

                    b.Property<int?>("Candidate2GirlId")
                        .HasColumnType("int");

                    b.Property<int?>("Candidate3GirlId")
                        .HasColumnType("int");

                    b.Property<int?>("Candidate4GirlId")
                        .HasColumnType("int");

                    b.Property<int?>("Candidate5GirlId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CandidateDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastDailyAdoptDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastDailyInteractionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastDailyRollDate")
                        .HasColumnType("date");

                    b.Property<int?>("TodayAdoptedGirlId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserDailyStates");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.UserGirl", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GirlId")
                        .HasColumnType("int");

                    b.Property<int>("Bond")
                        .HasColumnType("int");

                    b.Property<int>("Charm")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMetUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Focus")
                        .HasColumnType("int");

                    b.Property<int>("PersonalityTag")
                        .HasColumnType("int");

                    b.Property<int>("Vitality")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GirlId");

                    b.HasIndex("GirlId");

                    b.HasIndex("UserId", "DateMetUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UserGirls_UserId_DateMet_Desc");

                    b.HasIndex("UserId", "Bond", "DateMetUtc")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_UserGirls_UserId_Bond_DateMet");

                    b.ToTable("UserGirls");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.UserTownLocationUnlock", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TownLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "TownLocationId");

                    b.HasIndex("TownLocationId");

                    b.ToTable("UserTownLocationUnlocks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.Girl", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerGirlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.CompanionAssignment", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.TownLocation", "TownLocation")
                        .WithMany()
                        .HasForeignKey("TownLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.UserGirl", "UserGirl")
                        .WithOne()
                        .HasForeignKey("EverydayGirlsCompanionCollector.Models.Entities.CompanionAssignment", "UserId", "GirlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TownLocation");

                    b.Navigation("UserGirl");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.FriendRelationship", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", "Friend")
                        .WithMany("FriendOf")
                        .HasForeignKey("FriendUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.UserDailyState", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("EverydayGirlsCompanionCollector.Models.Entities.UserDailyState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.UserGirl", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.Girl", "Girl")
                        .WithMany()
                        .HasForeignKey("GirlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Girl");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.UserTownLocationUnlock", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.TownLocation", "TownLocation")
                        .WithMany()
                        .HasForeignKey("TownLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TownLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EverydayGirlsCompanionCollector.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("FriendOf");

                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
